In [9]:
import numpy as np
from nnunetv2.preprocessing.resampling.default_resampling import compute_new_shape

In [12]:
old_shape = np.array([44, 638, 638])
old_shape2 = np.array([44,574,574])
old_spacing = np.array([2.5, 0.625, 0.625])

In [16]:
compute_new_shape(old_shape, old_spacing, np.array([2.5, 0.9737296353754783, 0.9737296353754783]))

array([ 44, 410, 410])

In [17]:
compute_new_shape(old_shape, old_spacing, np.array([2.5, 1.0, 1.0]))

array([ 44, 399, 399])

In [18]:
compute_new_shape(old_shape, old_spacing, np.array([2.5, 1.25, 1.25]))

array([ 44, 319, 319])

In [19]:
compute_new_shape(old_shape, old_spacing, np.array([2.5, 1.5, 1.5]))

array([ 44, 266, 266])